// Package collaboration defines the user-level Grok Build role and workflow
// preset managed by Grok Build Switch. It stores configuration and file
// ownership only; agent runs, messages, and transcripts remain Grok Build's
// responsibility.
package collaboration

import (
	"encoding/hex"
	"fmt"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"grok_switch/internal/modelvariants"
	"grok_switch/internal/routing"
)

const (
	CurrentVersion      = 4
	ArtifactScopeUser   = "user"
	DefaultTierAdaptive = "adaptive"

	ModeSingleProvider = "single_provider"
	ModeFederated      = "federated"

	DataScopeRepositoryOnly = "repository_only"
	DataScopePriorWork      = "repository_plus_minimized_prior_work_products"

	FederationConsentBasisAllWorkflowTiersV1 = "all_workflow_tiers_v1"
	HandoffPolicyBounded                     = "bounded_work_products"
	NeverTransferCredentials                 = "credentials"
	NeverTransferSecrets                     = "secrets"
	NeverTransferTranscripts                 = "full_transcripts"

	TierEconomy         = "economy"
	TierFocusedEvidence = "focused-evidence"
	TierFocusedBuild    = "focused-build"
	TierAssurance       = "assurance"
	TierCritical        = "critical"

	RoleTaskDecomposition             = "task_decomposition"
	RoleMainImplementation            = "main_implementation"
	RoleDifficultImplementationReview = "difficult_implementation_review"
	RoleMainCoordinator               = "main_coordinator"

	SpeedTierStandard = modelvariants.SpeedTierStandard
	SpeedTierFast     = modelvariants.SpeedTierFast

	// These stable role IDs preserve ownership of artifacts generated by the
	// original three-role preset. Their descriptions and model assignments are
	// semantic in schema v4; the filenames no longer imply a fixed model.
	MainCoordinatorRoleName    = "gbs-terra-coordinator"
	TaskDecompositionRoleName  = "gbs-luna-evidence"
	MainImplementationRoleName = "gbs-main-implementation"
	DifficultReviewRoleName    = "gbs-sol-builder"
	WorkflowName               = "gbs-max-collab"
)

// RoleAssignment binds one semantic workflow responsibility to an explicit
// Standard route anchor, an independent speed tier, and a reasoning effort.
// The concrete Standard/Fast route is resolved against the current catalog at
// preview/apply/render time; the policy never stores a Fast route as its model.
type RoleAssignment struct {
	ProviderID      string `json:"provider_id"`
	Model           string `json:"model"`
	SpeedTier       string `json:"speed_tier"`
	ReasoningEffort string `json:"reasoning_effort"`
	DataScope       string `json:"data_scope"`
}

type HandoffEdge struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type TierHandoffEdges struct {
	Tier  string        `json:"tier"`
	Edges []HandoffEdge `json:"edges"`
}

type FederationConsent struct {
	Basis            string             `json:"basis"`
	ProviderIDs      []string           `json:"provider_ids"`
	HandoffPolicy    string             `json:"handoff_policy"`
	TierHandoffEdges []TierHandoffEdges `json:"tier_handoff_edges"`
	NeverTransfer    []string           `json:"never_transfer"`
}

// WorkflowPath is the single authoritative per-tier execution and data-flow
// contract. Roles defines serial execution order. DataFlows enumerates every
// produced packet consumed by a downstream role, including non-adjacent
// consumers; it is not inferred from execution adjacency.
type WorkflowPath struct {
	Tier      string        `json:"tier"`
	Budget    int           `json:"budget"`
	Roles     []string      `json:"roles"`
	DataFlows []HandoffEdge `json:"data_flows"`
}

var canonicalWorkflowPaths = []WorkflowPath{
	{Tier: TierEconomy, Budget: 1, Roles: []string{RoleMainCoordinator}, DataFlows: []HandoffEdge{}},
	{Tier: TierFocusedEvidence, Budget: 2, Roles: []string{RoleTaskDecomposition, RoleMainCoordinator}, DataFlows: []HandoffEdge{
		{From: RoleTaskDecomposition, To: RoleMainCoordinator},
	}},
	{Tier: TierFocusedBuild, Budget: 2, Roles: []string{RoleMainImplementation, RoleMainCoordinator}, DataFlows: []HandoffEdge{
		{From: RoleMainImplementation, To: RoleMainCoordinator},
	}},
	{Tier: TierAssurance, Budget: 3, Roles: []string{RoleTaskDecomposition, RoleMainImplementation, RoleMainCoordinator}, DataFlows: []HandoffEdge{
		{From: RoleTaskDecomposition, To: RoleMainImplementation},
		{From: RoleTaskDecomposition, To: RoleMainCoordinator},
		{From: RoleMainImplementation, To: RoleMainCoordinator},
	}},
	{Tier: TierCritical, Budget: 4, Roles: []string{RoleTaskDecomposition, RoleMainImplementation, RoleDifficultImplementationReview, RoleMainCoordinator}, DataFlows: []HandoffEdge{
		{From: RoleTaskDecomposition, To: RoleMainImplementation},
		{From: RoleTaskDecomposition, To: RoleDifficultImplementationReview},
		{From: RoleMainImplementation, To: RoleDifficultImplementationReview},
		{From: RoleTaskDecomposition, To: RoleMainCoordinator},
		{From: RoleMainImplementation, To: RoleMainCoordinator},
		{From: RoleDifficultImplementationReview, To: RoleMainCoordinator},
	}},
}

func WorkflowPaths() []WorkflowPath {
	out := make([]WorkflowPath, len(canonicalWorkflowPaths))
	for i, path := range canonicalWorkflowPaths {
		out[i] = WorkflowPath{
			Tier:      path.Tier,
			Budget:    path.Budget,
			Roles:     append([]string(nil), path.Roles...),
			DataFlows: append([]HandoffEdge{}, path.DataFlows...),
		}
	}
	return out
}

// RoleAssignments are intentionally independent from routing's generic
// default/explore/plan slots. Multiple roles may use the same Standard anchor
// while choosing different speed tiers and reasoning efforts.
type RoleAssignments struct {
	MainCoordinator               RoleAssignment `json:"main_coordinator"`
	TaskDecomposition             RoleAssignment `json:"task_decomposition"`
	MainImplementation            RoleAssignment `json:"main_implementation"`
	DifficultImplementationReview RoleAssignment `json:"difficult_implementation_review"`
}

// ResolvedRoleAssignment is the fail-closed runtime interpretation of one
// stored assignment. Route is the concrete alias written to Grok artifacts;
// StandardRoute is the stable anchor retained in collaboration.json.
type ResolvedRoleAssignment struct {
	Provider        routing.Provider
	StandardRoute   routing.ModelRoute
	Route           routing.ModelRoute
	SpeedTier       string
	ReasoningEffort string
}

// ResolvedRoleAssignments mirrors RoleAssignments after concrete route
// resolution. It is deliberately not persisted.
type ResolvedRoleAssignments struct {
	MainCoordinator               ResolvedRoleAssignment
	TaskDecomposition             ResolvedRoleAssignment
	MainImplementation            ResolvedRoleAssignment
	DifficultImplementationReview ResolvedRoleAssignment
}

// TierBudgets are exact logical-agent caps, not suggestions. The generated
// workflow refuses to run unless the caller supplies the matching agent_budget.
type TierBudgets struct {
	Economy   int `json:"economy"`
	Focused   int `json:"focused"`
	Assurance int `json:"assurance"`
	Critical  int `json:"critical"`
}

// ManagedArtifact records the last content hash written by the Switch. A file
// can be updated only while its current hash still matches this manifest.
type ManagedArtifact struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
}

// Policy is independent from routing schema v2. It references the active
// provider and Standard model anchors but never stores credentials or agent
// runtime data.
type Policy struct {
	Version           int                `json:"version"`
	Enabled           bool               `json:"enabled"`
	Mode              string             `json:"mode"`
	ProviderID        string             `json:"provider_id"`
	FederationConsent *FederationConsent `json:"federation_consent,omitempty"`
	Roles             RoleAssignments    `json:"roles"`
	DefaultTier       string             `json:"default_tier"`
	Budgets           TierBudgets        `json:"budgets"`
	MaxParallel       int                `json:"max_parallel"`
	RetryLimit        int                `json:"retry_limit"`
	ArtifactScope     string             `json:"artifact_scope"`
	ManagedArtifacts  []ManagedArtifact  `json:"managed_artifacts"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type roleEntry struct {
	Name       string
	Assignment RoleAssignment
}

func DefaultTierBudgets() TierBudgets {
	return TierBudgets{Economy: 1, Focused: 2, Assurance: 3, Critical: 4}
}

func NewPolicy(providerID string, roles RoleAssignments) Policy {
	providerID = strings.TrimSpace(providerID)
	for _, assignment := range []*RoleAssignment{&roles.MainCoordinator, &roles.TaskDecomposition, &roles.MainImplementation, &roles.DifficultImplementationReview} {
		if strings.TrimSpace(assignment.ProviderID) == "" {
			assignment.ProviderID = providerID
		}
	}
	if roles.TaskDecomposition.DataScope == "" {
		roles.TaskDecomposition.DataScope = DataScopeRepositoryOnly
	}
	for _, assignment := range []*RoleAssignment{&roles.MainCoordinator, &roles.MainImplementation, &roles.DifficultImplementationReview} {
		if assignment.DataScope == "" {
			assignment.DataScope = DataScopePriorWork
		}
	}
	return Policy{
		Version:       CurrentVersion,
		Enabled:       true,
		Mode:          ModeSingleProvider,
		ProviderID:    providerID,
		Roles:         normalizeRoleAssignments(roles),
		DefaultTier:   DefaultTierAdaptive,
		Budgets:       DefaultTierBudgets(),
		MaxParallel:   1,
		RetryLimit:    1,
		ArtifactScope: ArtifactScopeUser,
	}
}

func DisabledPolicy() Policy {
	return Policy{
		Version:       CurrentVersion,
		Enabled:       false,
		Mode:          ModeSingleProvider,
		DefaultTier:   DefaultTierAdaptive,
		Budgets:       DefaultTierBudgets(),
		MaxParallel:   1,
		RetryLimit:    1,
		ArtifactScope: ArtifactScopeUser,
	}
}

func (p Policy) Validate() error {
	if p.Version != CurrentVersion {
		return fmt.Errorf("unsupported collaboration policy version %d", p.Version)
	}
	if p.Mode != ModeSingleProvider && p.Mode != ModeFederated {
		return fmt.Errorf("invalid collaboration mode %q", p.Mode)
	}
	if p.Enabled {
		if strings.TrimSpace(p.ProviderID) == "" {
			return fmt.Errorf("collaboration coordinator provider_id is required")
		}
		if p.ProviderID == routing.OfficialProviderID {
			return fmt.Errorf("official provider does not expose configurable collaboration role routes")
		}
		for _, role := range p.Roles.entries() {
			if strings.TrimSpace(role.Assignment.ProviderID) == "" {
				return fmt.Errorf("%s provider_id is required", role.Name)
			}
			if role.Assignment.ProviderID == routing.OfficialProviderID {
				return fmt.Errorf("%s cannot use official provider", role.Name)
			}
			if strings.TrimSpace(role.Assignment.Model) == "" {
				return fmt.Errorf("%s model route is required", role.Name)
			}
			if role.Assignment.Model != strings.TrimSpace(role.Assignment.Model) {
				return fmt.Errorf("%s model route must not contain surrounding whitespace", role.Name)
			}
			speedTier := normalizeSpeedTier(role.Assignment.SpeedTier)
			if role.Assignment.SpeedTier != speedTier || !validSpeedTier(speedTier) {
				return fmt.Errorf("%s has invalid speed tier %q", role.Name, role.Assignment.SpeedTier)
			}
			effort := normalizeReasoningEffort(role.Assignment.ReasoningEffort)
			if role.Assignment.ReasoningEffort != effort || !validReasoningEffort(effort) {
				return fmt.Errorf("%s has invalid reasoning effort %q", role.Name, role.Assignment.ReasoningEffort)
			}
			if role.Assignment.DataScope != DataScopeRepositoryOnly && role.Assignment.DataScope != DataScopePriorWork {
				return fmt.Errorf("%s has invalid data scope %q", role.Name, role.Assignment.DataScope)
			}
		}
		if p.Roles.TaskDecomposition.DataScope != DataScopeRepositoryOnly {
			return fmt.Errorf("task decomposition data scope must be %q", DataScopeRepositoryOnly)
		}
		for name, scope := range map[string]string{"main coordinator": p.Roles.MainCoordinator.DataScope, "main implementation": p.Roles.MainImplementation.DataScope, "difficult implementation/review": p.Roles.DifficultImplementationReview.DataScope} {
			if scope != DataScopePriorWork {
				return fmt.Errorf("%s data scope must allow minimized prior work products", name)
			}
		}
		if p.Mode == ModeSingleProvider {
			if p.FederationConsent != nil {
				return fmt.Errorf("single_provider mode must not include federation consent")
			}
			for _, role := range p.Roles.entries() {
				if role.Assignment.ProviderID != p.ProviderID {
					return fmt.Errorf("single_provider mode requires every role to use coordinator provider %q", p.ProviderID)
				}
			}
		} else if err := p.validateFederationConsent(); err != nil {
			return err
		}
	}
	if !validDefaultTier(p.DefaultTier) {
		return fmt.Errorf("invalid collaboration default tier %q", p.DefaultTier)
	}
	if p.Budgets != DefaultTierBudgets() {
		return fmt.Errorf("collaboration budgets must be economy=1, focused=2, assurance=3, critical=4")
	}
	if p.MaxParallel != 1 {
		return fmt.Errorf("collaboration max_parallel must be 1")
	}
	if p.RetryLimit != 1 {
		return fmt.Errorf("collaboration retry_limit must be 1")
	}
	if p.ArtifactScope != ArtifactScopeUser {
		return fmt.Errorf("collaboration artifact scope must be %q", ArtifactScopeUser)
	}
	return validateManagedArtifacts(p.ManagedArtifacts)
}

// ResolveAgainstRouting resolves every stored Standard anchor to the concrete
// Standard/Fast route selected by its independent speed tier. Only the exact
// Switch-owned Codex registry and subscription provider source are trusted.
// Missing, ambiguous, unclassified, or forged relationships fail closed; Fast
// never silently falls back to Standard. Effort support is checked on the
// resolved concrete route rather than on the anchor.
func (p Policy) ResolveAgainstRouting(snapshot routing.Snapshot) (ResolvedRoleAssignments, error) {
	if err := p.Validate(); err != nil {
		return ResolvedRoleAssignments{}, err
	}
	if !p.Enabled {
		return ResolvedRoleAssignments{}, nil
	}
	if snapshot.ActiveProviderID != p.ProviderID {
		return ResolvedRoleAssignments{}, fmt.Errorf("collaboration coordinator provider %q is not the active provider %q", p.ProviderID, snapshot.ActiveProviderID)
	}
	if p.ProviderID == routing.OfficialProviderID {
		return ResolvedRoleAssignments{}, fmt.Errorf("official provider is not supported by this collaboration preset")
	}
	requireTrustedCodex := p.Mode == ModeSingleProvider
	mainCoordinator, err := resolveRoleAssignment("main coordinator", p.Roles.MainCoordinator, snapshot, requireTrustedCodex)
	if err != nil {
		return ResolvedRoleAssignments{}, err
	}
	taskDecomposition, err := resolveRoleAssignment("task decomposition", p.Roles.TaskDecomposition, snapshot, requireTrustedCodex)
	if err != nil {
		return ResolvedRoleAssignments{}, err
	}
	mainImplementation, err := resolveRoleAssignment("main implementation", p.Roles.MainImplementation, snapshot, requireTrustedCodex)
	if err != nil {
		return ResolvedRoleAssignments{}, err
	}
	difficultReview, err := resolveRoleAssignment("difficult implementation/review", p.Roles.DifficultImplementationReview, snapshot, requireTrustedCodex)
	if err != nil {
		return ResolvedRoleAssignments{}, err
	}
	return ResolvedRoleAssignments{
		MainCoordinator:               mainCoordinator,
		TaskDecomposition:             taskDecomposition,
		MainImplementation:            mainImplementation,
		DifficultImplementationReview: difficultReview,
	}, nil
}

// ValidateAgainstRouting retains the previous validation API while delegating
// all route interpretation to the central resolver.
func (p Policy) ValidateAgainstRouting(snapshot routing.Snapshot) error {
	_, err := p.ResolveAgainstRouting(snapshot)
	return err
}

func resolveRoleAssignment(name string, assignment RoleAssignment, snapshot routing.Snapshot, requireTrustedCodex bool) (ResolvedRoleAssignment, error) {
	provider, ok := snapshot.Provider(assignment.ProviderID)
	if !ok {
		return ResolvedRoleAssignment{}, fmt.Errorf("%s provider %q is unavailable", name, assignment.ProviderID)
	}
	standard, ok := routeByID(snapshot, assignment.Model)
	if !ok {
		return ResolvedRoleAssignment{}, fmt.Errorf("%s Standard route %q is unavailable", name, assignment.Model)
	}
	if standard.ProviderID != provider.ID {
		return ResolvedRoleAssignment{}, fmt.Errorf("%s route %q belongs to provider %q, not %q", name, assignment.Model, standard.ProviderID, provider.ID)
	}
	physicalID, trustedCodex, err := validateStandardRoute(provider, standard)
	if err != nil {
		return ResolvedRoleAssignment{}, fmt.Errorf("%s %w", name, err)
	}
	if requireTrustedCodex && !trustedCodex {
		return ResolvedRoleAssignment{}, fmt.Errorf("%s provider %q must be subscription-proxy:codex and use the exact trusted model registry", name, provider.ID)
	}

	concrete := standard
	switch assignment.SpeedTier {
	case SpeedTierStandard:
		// The Standard anchor is itself the concrete route. It injects no
		// priority service tier anywhere in Grok's generated role artifact.
	case SpeedTierFast:
		if !trustedCodex {
			return ResolvedRoleAssignment{}, fmt.Errorf("%s provider %q supports only Standard speed without an independently trusted variant registry", name, provider.ID)
		}
		matches := make([]routing.ModelRoute, 0, 1)
		for _, candidate := range snapshot.ModelRoutes {
			if candidate.ProviderID == provider.ID && candidate.SpeedTier == SpeedTierFast && candidate.StandardAnchor == standard.ID {
				matches = append(matches, candidate)
			}
		}
		if len(matches) == 0 {
			return ResolvedRoleAssignment{}, fmt.Errorf("%s Fast route for Standard anchor %q is unavailable; refusing to fall back to Standard", name, standard.ID)
		}
		if len(matches) != 1 {
			return ResolvedRoleAssignment{}, fmt.Errorf("%s Fast route for Standard anchor %q is ambiguous", name, standard.ID)
		}
		if err := validateTrustedFastRoute(provider, standard, matches[0], physicalID); err != nil {
			return ResolvedRoleAssignment{}, fmt.Errorf("%s %w", name, err)
		}
		concrete = matches[0]
	default:
		return ResolvedRoleAssignment{}, fmt.Errorf("%s has invalid speed tier %q", name, assignment.SpeedTier)
	}

	if !explicitlySupportsEffort(concrete, assignment.ReasoningEffort) {
		return ResolvedRoleAssignment{}, fmt.Errorf("%s model %q does not explicitly support reasoning effort %q", name, concrete.Name, assignment.ReasoningEffort)
	}
	return ResolvedRoleAssignment{
		Provider:        provider,
		StandardRoute:   standard,
		Route:           concrete,
		SpeedTier:       assignment.SpeedTier,
		ReasoningEffort: assignment.ReasoningEffort,
	}, nil
}

func validateStandardRoute(provider routing.Provider, route routing.ModelRoute) (string, bool, error) {
	if route.SpeedTier != SpeedTierStandard || route.StandardAnchor != route.ID {
		return "", false, fmt.Errorf("model route %q is not an explicit self-anchored Standard route", route.ID)
	}
	if provider.Source != "subscription-proxy:codex" {
		return "", false, nil
	}
	physicalID, ok := modelvariants.TrustedCodexPhysicalFromStandardAlias(route.ProfileModel)
	if !ok {
		return "", false, fmt.Errorf("Standard route %q is outside the exact trusted model registry", route.ID)
	}
	standardAlias, _ := modelvariants.CodexStandardAlias(physicalID)
	if route.ProfileModel != standardAlias || route.Model != standardAlias {
		return "", false, fmt.Errorf("Standard route %q does not resolve to its exact trusted alias", route.ID)
	}
	return physicalID, true, nil
}

func validateTrustedFastRoute(provider routing.Provider, standard, fast routing.ModelRoute, physicalID string) error {
	if provider.Source != "subscription-proxy:codex" || fast.ProviderID != provider.ID {
		return fmt.Errorf("Fast route %q is not owned by the trusted Codex subscription provider", fast.ID)
	}
	if fast.SpeedTier != SpeedTierFast || fast.StandardAnchor != standard.ID {
		return fmt.Errorf("Fast route %q does not explicitly anchor Standard route %q", fast.ID, standard.ID)
	}
	expectedAlias, _ := modelvariants.CodexFastAlias(physicalID)
	if fast.ProfileModel != expectedAlias || fast.Model != expectedAlias {
		return fmt.Errorf("Fast route %q does not resolve to the exact trusted Fast alias", fast.ID)
	}
	return nil
}

func (p Policy) CanonicalProviderIDs() []string {
	set := map[string]bool{}
	for _, role := range p.Roles.entries() {
		if role.Assignment.ProviderID != "" {
			set[role.Assignment.ProviderID] = true
		}
	}
	out := make([]string, 0, len(set))
	for id := range set {
		out = append(out, id)
	}
	sort.Strings(out)
	return out
}

func (p Policy) CanonicalTierHandoffEdges() []TierHandoffEdges {
	providers := map[string]string{
		RoleTaskDecomposition:             p.Roles.TaskDecomposition.ProviderID,
		RoleMainImplementation:            p.Roles.MainImplementation.ProviderID,
		RoleDifficultImplementationReview: p.Roles.DifficultImplementationReview.ProviderID,
		RoleMainCoordinator:               p.Roles.MainCoordinator.ProviderID,
	}
	out := make([]TierHandoffEdges, 0, len(canonicalWorkflowPaths))
	for _, path := range canonicalWorkflowPaths {
		edges := make([]HandoffEdge, 0, len(path.DataFlows))
		for _, flow := range path.DataFlows {
			if providers[flow.From] != "" && providers[flow.To] != "" && providers[flow.From] != providers[flow.To] {
				edges = append(edges, flow)
			}
		}
		out = append(out, TierHandoffEdges{Tier: path.Tier, Edges: edges})
	}
	return out
}

func (p Policy) validateFederationConsent() error {
	if p.FederationConsent == nil {
		return fmt.Errorf("federated mode requires explicit federation consent")
	}
	c := p.FederationConsent
	if c.Basis != FederationConsentBasisAllWorkflowTiersV1 {
		return fmt.Errorf("federation consent basis must be %q", FederationConsentBasisAllWorkflowTiersV1)
	}
	if c.HandoffPolicy != HandoffPolicyBounded {
		return fmt.Errorf("federation handoff_policy must be %q", HandoffPolicyBounded)
	}
	if !stringSliceEqual(c.ProviderIDs, p.CanonicalProviderIDs()) {
		return fmt.Errorf("federation consent provider_ids must exactly match the canonical selected provider set")
	}
	if !tierHandoffEdgesEqual(c.TierHandoffEdges, p.CanonicalTierHandoffEdges()) {
		return fmt.Errorf("federation consent tier_handoff_edges must exactly match every executable workflow path")
	}
	want := []string{NeverTransferCredentials, NeverTransferSecrets, NeverTransferTranscripts}
	if !stringSliceEqual(c.NeverTransfer, want) {
		return fmt.Errorf("federation never_transfer must exactly prohibit credentials, secrets, and full transcripts")
	}
	if len(c.ProviderIDs) < 2 {
		return fmt.Errorf("federated mode requires at least two providers")
	}
	return nil
}

func stringSliceEqual(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
func handoffEdgesEqual(a, b []HandoffEdge) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func tierHandoffEdgesEqual(a, b []TierHandoffEdges) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i].Tier != b[i].Tier || !handoffEdgesEqual(a[i].Edges, b[i].Edges) {
			return false
		}
	}
	return true
}

func (p Policy) UsesFast() bool {
	for _, role := range p.Roles.entries() {
		if role.Assignment.SpeedTier == SpeedTierFast {
			return true
		}
	}
	return false
}

func (r RoleAssignments) entries() []roleEntry {
	return []roleEntry{
		{Name: "main coordinator", Assignment: r.MainCoordinator},
		{Name: "task decomposition", Assignment: r.TaskDecomposition},
		{Name: "main implementation", Assignment: r.MainImplementation},
		{Name: "difficult implementation/review", Assignment: r.DifficultImplementationReview},
	}
}

func normalizeRoleAssignments(roles RoleAssignments) RoleAssignments {
	for _, assignment := range []*RoleAssignment{
		&roles.MainCoordinator,
		&roles.TaskDecomposition,
		&roles.MainImplementation,
		&roles.DifficultImplementationReview,
	} {
		assignment.ProviderID = strings.TrimSpace(assignment.ProviderID)
		assignment.Model = strings.TrimSpace(assignment.Model)
		assignment.SpeedTier = normalizeSpeedTier(assignment.SpeedTier)
		assignment.ReasoningEffort = normalizeReasoningEffort(assignment.ReasoningEffort)
		assignment.DataScope = strings.TrimSpace(assignment.DataScope)
	}
	return roles
}

func normalizeSpeedTier(speedTier string) string {
	return strings.ToLower(strings.TrimSpace(speedTier))
}

func validSpeedTier(speedTier string) bool {
	return speedTier == SpeedTierStandard || speedTier == SpeedTierFast
}

func normalizeReasoningEffort(effort string) string {
	return strings.ToLower(strings.TrimSpace(effort))
}

func validReasoningEffort(effort string) bool {
	switch effort {
	case "minimal", "low", "medium", "high", "xhigh", "max":
		return true
	default:
		return false
	}
}

func validDefaultTier(tier string) bool {
	switch tier {
	case DefaultTierAdaptive, "economy", "focused-evidence", "focused-build", "assurance", "critical":
		return true
	default:
		return false
	}
}

func routeByID(snapshot routing.Snapshot, id string) (routing.ModelRoute, bool) {
	for _, route := range snapshot.ModelRoutes {
		if route.ID == id {
			return route, true
		}
	}
	return routing.ModelRoute{}, false
}

func explicitlySupportsEffort(route routing.ModelRoute, effort string) bool {
	effort = normalizeReasoningEffort(effort)
	if !validReasoningEffort(effort) || !route.SupportsReasoningEffort {
		return false
	}
	source := strings.ToLower(strings.TrimSpace(route.ReasoningEffortsSource))
	if source != "declared" && source != "probe" {
		return false
	}
	for _, supported := range route.ReasoningEfforts {
		if normalizeReasoningEffort(supported) == effort {
			return true
		}
	}
	return false
}

func validateManagedArtifacts(artifacts []ManagedArtifact) error {
	seen := make(map[string]bool, len(artifacts))
	for _, artifact := range artifacts {
		path := filepath.Clean(strings.TrimSpace(artifact.Path))
		if path == "." || !filepath.IsAbs(path) {
			return fmt.Errorf("managed artifact path must be absolute: %q", artifact.Path)
		}
		if seen[path] {
			return fmt.Errorf("duplicate managed artifact path %q", path)
		}
		seen[path] = true
		if !validSHA256(artifact.SHA256) {
			return fmt.Errorf("managed artifact %q has invalid SHA-256", path)
		}
	}
	return nil
}

func validSHA256(value string) bool {
	if len(value) != 64 || strings.ToLower(value) != value {
		return false
	}
	decoded, err := hex.DecodeString(value)
	return err == nil && len(decoded) == 32
}

func clonePolicy(policy Policy) Policy {
	out := policy
	out.ManagedArtifacts = append([]ManagedArtifact(nil), policy.ManagedArtifacts...)
	return out
}
