package collaboration

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"grok_switch/internal/routing"
)

// ArtifactPaths lists the only files managed by the collaboration preset.
// Three legacy basenames remain stable so an upgrade keeps ownership instead
// of orphaning files previously generated by the Switch.
type ArtifactPaths struct {
	MainCoordinatorRole     string
	TaskDecompositionRole   string
	MainImplementationRole  string
	DifficultReviewRole     string
	MainCoordinatorAgent    string
	TaskDecompositionAgent  string
	MainImplementationAgent string
	DifficultReviewAgent    string
	Workflow                string
}

func ArtifactPathsForGrokHome(grokHome string) ArtifactPaths {
	return ArtifactPaths{
		MainCoordinatorRole:     filepath.Join(grokHome, "roles", MainCoordinatorRoleName+".toml"),
		TaskDecompositionRole:   filepath.Join(grokHome, "roles", TaskDecompositionRoleName+".toml"),
		MainImplementationRole:  filepath.Join(grokHome, "roles", MainImplementationRoleName+".toml"),
		DifficultReviewRole:     filepath.Join(grokHome, "roles", DifficultReviewRoleName+".toml"),
		MainCoordinatorAgent:    filepath.Join(grokHome, "agents", MainCoordinatorRoleName+".md"),
		TaskDecompositionAgent:  filepath.Join(grokHome, "agents", TaskDecompositionRoleName+".md"),
		MainImplementationAgent: filepath.Join(grokHome, "agents", MainImplementationRoleName+".md"),
		DifficultReviewAgent:    filepath.Join(grokHome, "agents", DifficultReviewRoleName+".md"),
		Workflow:                filepath.Join(grokHome, "workflows", WorkflowName+".rhai"),
	}
}

func (p ArtifactPaths) Validate() error {
	seen := map[string]bool{}
	for label, path := range map[string]string{
		"main coordinator role":     p.MainCoordinatorRole,
		"task decomposition role":   p.TaskDecompositionRole,
		"main implementation role":  p.MainImplementationRole,
		"difficult review role":     p.DifficultReviewRole,
		"main coordinator agent":    p.MainCoordinatorAgent,
		"task decomposition agent":  p.TaskDecompositionAgent,
		"main implementation agent": p.MainImplementationAgent,
		"difficult review agent":    p.DifficultReviewAgent,
		"workflow":                  p.Workflow,
	} {
		clean := filepath.Clean(strings.TrimSpace(path))
		if clean == "." || !filepath.IsAbs(clean) {
			return fmt.Errorf("%s artifact path must be absolute", label)
		}
		if seen[clean] {
			return fmt.Errorf("duplicate collaboration artifact path %q", clean)
		}
		seen[clean] = true
	}
	return nil
}

func (p ArtifactPaths) CanonicalPaths() []string {
	return []string{
		filepath.Clean(p.MainCoordinatorRole),
		filepath.Clean(p.TaskDecompositionRole),
		filepath.Clean(p.MainImplementationRole),
		filepath.Clean(p.DifficultReviewRole),
		filepath.Clean(p.MainCoordinatorAgent),
		filepath.Clean(p.TaskDecompositionAgent),
		filepath.Clean(p.MainImplementationAgent),
		filepath.Clean(p.DifficultReviewAgent),
		filepath.Clean(p.Workflow),
	}
}

// LegacyCanonicalPaths is the exact five-file manifest emitted before agent
// definitions were added. It remains accepted only as an upgrade source; the
// next enabled apply renders and persists the complete nine-file manifest.
func (p ArtifactPaths) LegacyCanonicalPaths() []string {
	return []string{
		filepath.Clean(p.MainCoordinatorRole),
		filepath.Clean(p.TaskDecompositionRole),
		filepath.Clean(p.MainImplementationRole),
		filepath.Clean(p.DifficultReviewRole),
		filepath.Clean(p.Workflow),
	}
}

// ValidateCanonicalManifest rejects partial, extra, duplicate, or relocated
// ownership before an existing policy is used to plan another apply. The exact
// legacy five-file set is accepted so it can be transactionally upgraded.
func ValidateCanonicalManifest(manifest []ManagedArtifact, paths ArtifactPaths) error {
	if err := paths.Validate(); err != nil {
		return err
	}
	if err := validateManagedArtifacts(manifest); err != nil {
		return err
	}
	actual := make(map[string]struct{}, len(manifest))
	for _, artifact := range manifest {
		actual[filepath.Clean(artifact.Path)] = struct{}{}
	}
	if manifestMatchesCanonicalSet(actual, len(manifest), paths.CanonicalPaths()) || manifestMatchesCanonicalSet(actual, len(manifest), paths.LegacyCanonicalPaths()) {
		return nil
	}

	allowed := make(map[string]struct{}, len(paths.CanonicalPaths()))
	for _, path := range paths.CanonicalPaths() {
		allowed[path] = struct{}{}
	}
	for path := range actual {
		if _, ok := allowed[path]; !ok {
			return fmt.Errorf("managed artifact manifest 包含非 canonical 路径 %q", path)
		}
	}
	return fmt.Errorf("managed artifact manifest 必须恰好包含 9 个当前 canonical 路径或 5 个 legacy canonical 路径，当前为 %d 个", len(manifest))
}

func manifestMatchesCanonicalSet(actual map[string]struct{}, actualLen int, expected []string) bool {
	if actualLen != len(expected) {
		return false
	}
	for _, path := range expected {
		if _, ok := actual[path]; !ok {
			return false
		}
	}
	return true
}

// RenderedArtifact is a complete desired file. The renderer never writes it.
type RenderedArtifact struct {
	Path    string `json:"path"`
	Content []byte `json:"-"`
	SHA256  string `json:"sha256"`
}

func Hash(content []byte) string {
	sum := sha256.Sum256(content)
	return hex.EncodeToString(sum[:])
}

func RenderArtifacts(policy Policy, snapshot routing.Snapshot, paths ArtifactPaths) ([]RenderedArtifact, error) {
	resolved, err := policy.ResolveAgainstRouting(snapshot)
	if err != nil {
		return nil, err
	}
	if err := paths.Validate(); err != nil {
		return nil, err
	}

	artifacts := []RenderedArtifact{
		renderedArtifact(paths.MainCoordinatorRole, renderRole(
			"Main coordinator for scope control, reconciliation, verification, and final delivery",
			"all",
			resolved.MainCoordinator.Route.Name,
			resolved.MainCoordinator.ReasoningEffort,
		)),
		renderedArtifact(paths.TaskDecompositionRole, renderRole(
			"Read-only task decomposer that maps constraints, dependencies, files, acceptance criteria, and focused tests",
			"read-only",
			resolved.TaskDecomposition.Route.Name,
			resolved.TaskDecomposition.ReasoningEffort,
		)),
		renderedArtifact(paths.MainImplementationRole, renderRole(
			"Main implementer for scoped code changes and focused verification",
			"all",
			resolved.MainImplementation.Route.Name,
			resolved.MainImplementation.ReasoningEffort,
		)),
		renderedArtifact(paths.DifficultReviewRole, renderRole(
			"Specialist for difficult implementation, debugging, adversarial review, and critical fixes",
			"all",
			resolved.DifficultImplementationReview.Route.Name,
			resolved.DifficultImplementationReview.ReasoningEffort,
		)),
		renderedArtifact(paths.MainCoordinatorAgent, renderAgentDefinition(
			MainCoordinatorRoleName,
			"Main coordinator for scope control, reconciliation, verification, and final delivery",
			"default",
		)),
		renderedArtifact(paths.TaskDecompositionAgent, renderAgentDefinition(
			TaskDecompositionRoleName,
			"Read-only task decomposer that maps constraints, dependencies, files, acceptance criteria, and focused tests",
			"plan",
		)),
		renderedArtifact(paths.MainImplementationAgent, renderAgentDefinition(
			MainImplementationRoleName,
			"Main implementer for scoped code changes and focused verification",
			"default",
		)),
		renderedArtifact(paths.DifficultReviewAgent, renderAgentDefinition(
			DifficultReviewRoleName,
			"Specialist for difficult implementation, debugging, adversarial review, and critical fixes",
			"default",
		)),
		renderedArtifact(paths.Workflow, renderWorkflow(
			resolved.MainCoordinator.Route.Name,
			resolved.TaskDecomposition.Route.Name,
			resolved.MainImplementation.Route.Name,
			resolved.DifficultImplementationReview.Route.Name,
		)),
	}
	return artifacts, nil
}

func ManifestForArtifacts(artifacts []RenderedArtifact) []ManagedArtifact {
	manifest := make([]ManagedArtifact, 0, len(artifacts))
	for _, artifact := range artifacts {
		manifest = append(manifest, ManagedArtifact{Path: filepath.Clean(artifact.Path), SHA256: artifact.SHA256})
	}
	sort.Slice(manifest, func(i, j int) bool { return manifest[i].Path < manifest[j].Path })
	return manifest
}

func renderedArtifact(path string, content []byte) RenderedArtifact {
	return RenderedArtifact{Path: filepath.Clean(path), Content: content, SHA256: Hash(content)}
}

func renderRole(description, capability, model, reasoningEffort string) []byte {
	var b strings.Builder
	b.WriteString("# Managed by Grok Build Switch. Edit through the Switch or disable the preset before taking ownership.\n")
	b.WriteString("description = ")
	b.WriteString(strconv.Quote(description))
	b.WriteByte('\n')
	b.WriteString("default_capability_mode = ")
	b.WriteString(strconv.Quote(capability))
	b.WriteByte('\n')
	b.WriteString("model = ")
	b.WriteString(strconv.Quote(model))
	b.WriteByte('\n')
	b.WriteString("reasoning_effort = ")
	b.WriteString(strconv.Quote(reasoningEffort))
	b.WriteByte('\n')
	return []byte(b.String())
}

// renderAgentDefinition registers the stable gbs-* name as an actual subagent
// type. Role TOML files are resolution overlays; Grok Build discovers custom
// agent types only from ~/.grok/agents/*.md (or the project equivalent).
func renderAgentDefinition(name, description, permissionMode string) []byte {
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("name: ")
	b.WriteString(name)
	b.WriteByte('\n')
	b.WriteString("description: ")
	b.WriteString(strconv.Quote(description))
	b.WriteByte('\n')
	b.WriteString("prompt_mode: full\n")
	b.WriteString("model: inherit\n")
	b.WriteString("permission_mode: ")
	b.WriteString(permissionMode)
	b.WriteByte('\n')
	b.WriteString("agents_md: true\n")
	b.WriteString("---\n\n")
	b.WriteString("Execute the assigned Collaboration role directly. Follow the workflow prompt, inspect the actual workspace before making claims, preserve unrelated user work, and do not perform destructive or shared external actions without explicit user approval.\n")
	return []byte(b.String())
}

func renderWorkflow(coordinatorModel, decompositionModel, implementationModel, difficultReviewModel string) []byte {
	paths := WorkflowPaths()
	var b strings.Builder
	b.WriteString("let meta = #{\n")
	b.WriteString("    name: \"gbs-max-collab\",\n")
	b.WriteString("    description: \"Four-role collaboration with exact serial budgets. Do not launch this named workflow directly from slash autocomplete: named slash launches use budget 128. Ask Grok to run gbs-max-collab with an explicit objective and tier so it can call the workflow tool with agent_budget 1/2/3/4.\",\n")
	b.WriteString("    when_to_use: \"Ask Grok in natural language: Use Economy, Focused Evidence, Focused Build, Assurance, or Critical to run gbs-max-collab, objective: <task>. Grok must pass args.objective, args.tier, and the matching agent_budget through the workflow tool.\",\n")
	b.WriteString("    phases: [\n")
	b.WriteString("        #{ title: \"Decompose\", detail: \"optional read-only task decomposition\" },\n")
	b.WriteString("        #{ title: \"Implement\", detail: \"optional main implementation\" },\n")
	b.WriteString("        #{ title: \"Review\", detail: \"optional difficult implementation and critical review\" },\n")
	b.WriteString("        #{ title: \"Coordinate\", detail: \"final reconciliation, verification, and delivery\" },\n")
	b.WriteString("    ],\n")
	b.WriteString("};\n\n")
	b.WriteString("let objective = if args == () { () } else { args.objective };\n")
	b.WriteString("let tier = if args == () { () } else { args.tier };\n")
	b.WriteString("if objective == () || type_of(objective) != \"string\" || objective == \"\" {\n")
	b.WriteString("    pause(\"verification\", \"Pass args.objective as a non-empty string.\");\n")
	b.WriteString("}\n")
	b.WriteString("if tier == () || type_of(tier) != \"string\" {\n")
	b.WriteString("    pause(\"verification\", \"Pass args.tier: economy, focused-evidence, focused-build, assurance, or critical.\");\n")
	b.WriteString("}\n\n")
	b.WriteString("let expected_budget = 0;\n")
	for i, path := range paths {
		if i == 0 {
			b.WriteString("if tier == ")
		} else {
			b.WriteString("else if tier == ")
		}
		b.WriteString(strconv.Quote(path.Tier))
		b.WriteString(" { expected_budget = ")
		b.WriteString(strconv.Itoa(path.Budget))
		b.WriteString("; }\n")
	}
	b.WriteString("else { pause(\"verification\", \"Unknown tier. Use economy, focused-evidence, focused-build, assurance, or critical.\"); }\n")
	b.WriteString("let run_budget = budget();\n")
	b.WriteString("if run_budget.total != expected_budget {\n")
	b.WriteString("    pause(\"verification\", \"This workflow fails closed unless agent_budget exactly matches the selected tier (1/2/3/4). Launch it through the workflow tool with the matching cap; the default slash-command budget is intentionally rejected.\");\n")
	b.WriteString("}\n\n")
	b.WriteString("let quoted_objective = json_encode(objective);\n")
	b.WriteString("let decomposition_packet = \"\";\n")
	b.WriteString("let implementation_packet = \"\";\n")
	b.WriteString("let review_packet = \"\";\n\n")
	b.WriteString("if " + tierRoleCondition(paths, RoleTaskDecomposition) + " {\n")
	b.WriteString("    phase(\"Decompose\");\n")
	b.WriteString("    let decomposition_prompt = \"Decompose this objective after inspecting the actual workspace with read-only tools: \" + quoted_objective + \". Return a minimized repository work product containing: (1) relevant files and line references, (2) confirmed constraints and dependencies, (3) ordered work units, (4) acceptance criteria and minimum tests, (5) risks and unknowns, and (6) the smallest file set the implementer should read. Do not edit files and do not perform external actions.\";\n")
	b.WriteString("    let decomposition_result = agent(decomposition_prompt, #{ label: \"decompose:task\", agent_type: \"gbs-luna-evidence\", model: ")
	b.WriteString(strconv.Quote(decompositionModel))
	b.WriteString(", capability_mode: \"read-only\" });\n")
	b.WriteString("    if decomposition_result != () && decomposition_result.success { decomposition_packet = decomposition_result.output; }\n")
	b.WriteString("    else { pause(\"verification\", \"Task decomposition failed; no later stage was launched.\"); }\n")
	b.WriteString("}\n\n")
	b.WriteString("if " + tierRoleCondition(paths, RoleMainImplementation) + " {\n")
	b.WriteString("    phase(\"Implement\");\n")
	b.WriteString("    let implementation_prompt = \"Implement this objective in the actual workspace: \" + quoted_objective + \".\";\n")
	if workflowConsumes(paths, RoleTaskDecomposition, RoleMainImplementation) {
		b.WriteString("    if decomposition_packet != \"\" { implementation_prompt += \" Consume only this minimized task-decomposition work product; do not request or reproduce credentials, secrets, unrelated files, or full transcript: \" + json_encode(decomposition_packet) + \".\"; }\n")
	}
	b.WriteString("    implementation_prompt += \" Inspect the current git diff before editing, preserve unrelated user work, make only scoped local changes, run focused tests, and return changed files, verification results, risks, and remaining assumptions. Treat destructive or shared external actions as blocked pending user approval.\";\n")
	b.WriteString("    let implementation_result = agent(implementation_prompt, #{ label: \"implement:main\", agent_type: \"gbs-main-implementation\", model: ")
	b.WriteString(strconv.Quote(implementationModel))
	b.WriteString(", capability_mode: \"all\" });\n")
	b.WriteString("    if implementation_result != () && implementation_result.success { implementation_packet = implementation_result.output; }\n")
	b.WriteString("    else { pause(\"verification\", \"Main implementation failed; no later stage was launched.\"); }\n")
	b.WriteString("}\n\n")
	b.WriteString("if " + tierRoleCondition(paths, RoleDifficultImplementationReview) + " {\n")
	b.WriteString("    phase(\"Review\");\n")
	b.WriteString("    let review_prompt = \"Handle difficult implementation and perform an adversarial technical review for this objective: \" + quoted_objective + \". Re-open the actual files, current git diff, and relevant tests independently.\";\n")
	if workflowConsumes(paths, RoleTaskDecomposition, RoleDifficultImplementationReview) {
		b.WriteString("    if decomposition_packet != \"\" { review_prompt += \" Minimized task-decomposition work product (omit credentials, secrets, unrelated files, and full transcript): \" + json_encode(decomposition_packet) + \".\"; }\n")
	}
	if workflowConsumes(paths, RoleMainImplementation, RoleDifficultImplementationReview) {
		b.WriteString("    if implementation_packet != \"\" { review_prompt += \" Minimized main-implementation work product (omit credentials, secrets, unrelated files, and full transcript): \" + json_encode(implementation_packet) + \".\"; }\n")
	}
	b.WriteString("    review_prompt += \" Fix local reversible correctness issues you confirm, run focused verification, and return concrete findings, fixes, tests, and anything still unverified. Do not perform destructive or shared external actions without user approval.\";\n")
	b.WriteString("    let review_result = agent(review_prompt, #{ label: \"review:difficult\", agent_type: \"gbs-sol-builder\", model: ")
	b.WriteString(strconv.Quote(difficultReviewModel))
	b.WriteString(", capability_mode: \"all\" });\n")
	b.WriteString("    if review_result != () && review_result.success { review_packet = review_result.output; }\n")
	b.WriteString("    else { pause(\"verification\", \"Difficult implementation/review failed; final coordination was not launched.\"); }\n")
	b.WriteString("}\n\n")
	b.WriteString("phase(\"Coordinate\");\n")
	b.WriteString("let coordinate_prompt = \"Complete this objective as the main coordinator: \" + quoted_objective + \". Inspect current files and git diff before acting. In Economy or decomposition-only paths, perform any remaining scoped implementation yourself. Reconcile supplied packets against the actual workspace, preserve unrelated user work, run the minimum relevant verification, and produce a concise final result. Never perform destructive or shared external actions without explicit user approval.\";\n")
	if workflowConsumes(paths, RoleTaskDecomposition, RoleMainCoordinator) {
		b.WriteString("if decomposition_packet != \"\" { coordinate_prompt += \" Minimized task-decomposition work product (omit credentials, secrets, unrelated files, and full transcript): \" + json_encode(decomposition_packet) + \".\"; }\n")
	}
	if workflowConsumes(paths, RoleMainImplementation, RoleMainCoordinator) {
		b.WriteString("if implementation_packet != \"\" { coordinate_prompt += \" Minimized main-implementation work product (omit credentials, secrets, unrelated files, and full transcript): \" + json_encode(implementation_packet) + \".\"; }\n")
	}
	if workflowConsumes(paths, RoleDifficultImplementationReview, RoleMainCoordinator) {
		b.WriteString("if review_packet != \"\" { coordinate_prompt += \" Minimized difficult-review work product (omit credentials, secrets, unrelated files, and full transcript): \" + json_encode(review_packet) + \".\"; }\n")
	}
	b.WriteString("let coordinate_result = agent(coordinate_prompt, #{ label: \"coordinate:main\", agent_type: \"gbs-terra-coordinator\", model: ")
	b.WriteString(strconv.Quote(coordinatorModel))
	b.WriteString(", capability_mode: \"all\" });\n")
	b.WriteString("if coordinate_result == () || !coordinate_result.success { pause(\"verification\", \"Main coordination failed.\"); }\n")
	b.WriteString("complete(#{ tier: tier, agent_budget: expected_budget, result: coordinate_result.output });\n")
	return []byte(b.String())
}

func tierRoleCondition(paths []WorkflowPath, role string) string {
	conditions := make([]string, 0, len(paths))
	for _, path := range paths {
		for _, candidate := range path.Roles {
			if candidate == role {
				conditions = append(conditions, "tier == "+strconv.Quote(path.Tier))
				break
			}
		}
	}
	return strings.Join(conditions, " || ")
}

func workflowConsumes(paths []WorkflowPath, from, to string) bool {
	for _, path := range paths {
		for _, flow := range path.DataFlows {
			if flow.From == from && flow.To == to {
				return true
			}
		}
	}
	return false
}
